name: tiny_fests_app
description: "Tiny Fests: A joyful, magical event booking app."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8

  # API & ENV
  http: ^1.2.0
  flutter_dotenv: ^5.1.0

  # State Management
  provider: ^6.1.1

  # Caching / Local Storage
  shared_preferences: ^2.2.2

  # UI
  cached_network_image: ^3.3.1
  fluttertoast: ^8.2.4
  intl: ^0.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true


